### ISSUE TITLE
Main message table

### ISSUE THREAD

**Issue by Hoi15A** [PROGRADE-Tech/Tarchivebot#11]
The first thing that will be seen on the frontend. A table of all message data received neatly displayed with basic filtering and search.

<hr>

**TODO:**
- [x] Display data in table
- [x] Make table searchable
- [x] Make table sortable
- [x] Make the table look like a proper table (scss)

**Comment by fuerbringer** [comment]
To be clear, is this currently worked on in the branch `main-table`? Thanks

**Comment by Hoi15A** [comment]
@fuerbringer exactly

**Comment by fuerbringer** [comment]
Related #8

**Comment by fuerbringer** [comment]
Solved by #32
